import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    const val com_github_johnrengelman_shadow_gradle_plugin: String =
            "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:" +
            Versions.com_github_johnrengelman_shadow_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val nebula_clojure_gradle_plugin: String =
            "nebula.clojure:nebula.clojure.gradle.plugin:" + Versions.nebula_clojure_gradle_plugin

    /**
     * https://github.com/mikera/clojure-pom */
    const val cljunit: String = "net.mikera:cljunit:" + Versions.cljunit

    /**
     * git@github.com:mikera/${project.artifactId}.git */
    const val mathz: String = "net.mikera:mathz:" + Versions.mathz

    /**
     * https://github.com/mikera/${project.artifactId} */
    const val mikera: String = "net.mikera:mikera:" + Versions.mikera

    /**
     * https://github.com/mikera/${project.artifactId}.git */
    const val orculje: String = "net.mikera:orculje:" + Versions.orculje

    /**
     * https://github.com/mikera/${project.artifactId}.git */
    const val swing_console: String = "net.mikera:swing-console:" + Versions.swing_console

    /**
     * http://clojure.org/ */
    const val clojure: String = "org.clojure:clojure:" + Versions.clojure

    /**
     * https://github.com/clojure/build.poms */
    const val math_combinatorics: String = "org.clojure:math.combinatorics:" +
            Versions.math_combinatorics
}
